# Generated by Django 3.2.9 on 2021-11-29 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propert_value',
            name='NOI_calculations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value', to='value.noi'),
        ),
        migrations.AlterField(
            model_name='propert_value',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value', to='value.property'),
        ),
    ]
