# Generated by Django 3.2.9 on 2021-11-29 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0002_auto_20211129_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expanse', to='value.property'),
        ),
        migrations.AlterField(
            model_name='noi',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noi', to='value.property'),
        ),
        migrations.AlterField(
            model_name='total_noi',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_noi', to='value.property'),
        ),
    ]
